version: "3.9"

services:
  angular:
    build: ./frontend
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app
    depends_on:
      - symfony

  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    volumes:
      - ./backend:/backend
    environment:
      - DATABASE_URL=mysql://root:techbuy@mysql:3306/techbuy?serverVersion=8&charset=utf8mb4
    depends_on:
      - mysql
    command: bash -c "composer install && php -S 0.0.0.0:8081 -t public/"
    networks:
      - symfony
# added the command to install the composer when running multiple containers
  mysql:
    image: mariadb:10.6.12
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: techbuy
    networks:
      - symfony
    ports:
      - 3307:3306
    volumes:
      - ./data:/docker-entrypoint-initdb.d
      - ./mysql:/var/lib/mysql

networks:
  symfony:

volumes:
  data: